#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
crawlable/build_tables.py — generate crawlable/tables_authority.json from the verified
representation (mechanical, no hand-transcription — "mechanical before model", D5/§5.6).

Reads representation TBL-AUTH-ESTANDAR / TBL-AUTH-CASEUW / TBL-AUTH-LICITACIONES (verbatim_table)
and emits matrix_lookup tables with parsed numeric limits (string Bs values -> int BOB,
"No aplica" -> null, "05" -> 5). Re-run if the representation changes.
"""
import json, os
import sys
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")  # print UTF-8 regardless of locale (avoids UnicodeEncodeError on —/✓/→/accents)


ROOT = os.path.dirname(os.path.abspath(__file__))
REP = os.path.join(os.path.dirname(ROOT), "representation", "underwriting_manual", "tables.json")
rep = {t["id"]: t for t in json.load(open(REP, encoding="utf-8"))["tables"]}

def money(s):
    # "3.480.000,00" -> 3480000 ; "1.750.000" -> 1750000
    return int(float(s.strip().replace(".", "").replace(",", ".")))

def count(s):
    s = s.strip()
    return None if s.lower() == "no aplica" else int(s)

def matrix(tid, suscriptor_i, count_i, valor_i):
    t = rep[tid]
    rows = [{"suscriptor": r[suscriptor_i],
             "max_vehiculos": count(r[count_i]),
             "max_valor_bob": money(r[valor_i]),
             "max_valor_verbatim": r[valor_i]} for r in t["rows"]]
    return {
        "role": "matrix_lookup",
        "name": t["name"],
        "lookup_key": "suscriptor",
        "rows": rows,
        "source": {"section": t["source"]["section"], "pdf_page": t["source"]["pdf_page"],
                   "printed_page": t["source"]["printed_page"], "version": "3.0"},
        "provenance": t.get("provenance", "verbatim_table"),
        "_origin": {"artifact": "tables.json", "source_id": tid},
    }

out = {
    "_material_class": "parameters — authority matrices (matrix_lookup), generated by build_tables.py",
    "_note": "Suscripción authority per process (Estándar/Case UW/Licitaciones). Consumed by `authority` nodes. Values parsed from representation verbatim_table; max_valor_verbatim keeps the source string. The Lizeth Rios row differs between Case UW (100 / 1.400.000) and Licitaciones (10 / 700.000) — preserved, flagged to RUL-LIZETH-RIOS-AUTH.",
    "_doc_conflicts": [{"ledger_ref": "rulings/RUL-MAN-VERSION.md", "note": "version '3.0' literal page stamp; cover/changelog say '4.0'."}],
    "TBL-AUTH-ESTANDAR": matrix("TBL-AUTH-ESTANDAR", 0, 1, 2),
    "TBL-AUTH-CASEUW": matrix("TBL-AUTH-CASEUW", 0, 1, 2),
    "TBL-AUTH-LICITACIONES": matrix("TBL-AUTH-LICITACIONES", 0, 1, 2),
}
# flag the Lizeth Rios cross-table discrepancy on the two affected tables
for tid in ("TBL-AUTH-CASEUW", "TBL-AUTH-LICITACIONES"):
    out[tid]["cross_table_conflicts"] = [{
        "row_key": "Lizeth Rios",
        "detail": "Case UW: 100 / 1.400.000,00 vs Licitaciones: 10 / 700.000,00 para el mismo suscriptor. La fuente no indica errata; ambas se conservan.",
        "ledger_ref": "rulings/RUL-LIZETH-RIOS-AUTH.md"}]

path = os.path.join(ROOT, "tables_authority.json")
json.dump(out, open(path, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print(f"wrote {path}: "
      + ", ".join(f"{k}={len(v['rows'])} rows" for k, v in out.items() if isinstance(v, dict) and v.get("rows")))
