#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
crawlable/build_reference.py — capture the non-branch normative rules as a reference record.

Reads representation/underwriting_manual/rules.json + rule_buckets.json, and for every rule in
the `reference` bucket emits a record with its verbatim trigger (quote_verbatim, copied not
retyped), source anchor, class, and _origin. These rules are normative but not branch-shaped
(governance / coverage terms / procedural / info requirements / process descriptions / formula /
CRM tarificación) — captured in crawlable/ so the coverage manifest accounts for them, without
inventing graph structure the source does not have (decisions.md D1/D2). Also asserts the buckets
partition all 84 rules.
"""
import json, os
import sys
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")  # print UTF-8 regardless of locale (avoids UnicodeEncodeError on —/✓/→/accents)


ROOT = os.path.dirname(os.path.abspath(__file__))
rules = {r["id"]: r for r in json.load(open(os.path.join(
    os.path.dirname(ROOT), "representation", "underwriting_manual", "rules.json"), encoding="utf-8"))["rules"]}
buckets = json.load(open(os.path.join(ROOT, "rule_buckets.json"), encoding="utf-8"))

# --- assert the buckets partition every rule exactly once ---
node = set(buckets["node_converted"]); tree = set(buckets["tree_converted"])
partial = set(buckets["partial_router"]); deferred = set(buckets["deferred"])
table = set(buckets["table_realized"]); ref = set(buckets["reference"])
allb = [node, tree, partial, deferred, table, ref]
union = set().union(*allb)
overlaps = [a & b for i, a in enumerate(allb) for b in allb[i+1:] if a & b]
assert not overlaps, f"buckets overlap: {overlaps}"
missing = set(rules) - union
extra = union - set(rules)
assert not missing and not extra, f"partition broken — missing {sorted(missing)} / extra {sorted(extra)}"

out = {
    "_material_class": "non-branch normative rules, captured verbatim (generated by build_reference.py)",
    "_note": "Rules whose content is normative but not branch-shaped (decisions.md D1/D2). Captured here verbatim with class + source so the coverage manifest accounts for them; NOT executable graph nodes. Decisional rules are in graph/; rating values are in tables*.json.",
    "rules": []
}
for rid in sorted(ref):
    r = rules[rid]
    out["rules"].append({
        "id": rid,
        "class": buckets["reference"][rid],
        "applies_to": r.get("applies_to"),
        "source": {**r.get("source", {}), "version": "3.0"},
        "source_quote": r.get("quote_verbatim", ""),
        "_origin": {"artifact": "rules.json", "source_id": rid}
    })

json.dump(out, open(os.path.join(ROOT, "reference.json"), "w", encoding="utf-8"),
          ensure_ascii=False, indent=1)
print(f"wrote reference.json: {len(out['rules'])} non-branch rules captured")
print(f"bucket partition OK — node {len(node)} + tree {len(tree)} + partial {len(partial)} + "
      f"deferred {len(deferred)} + table {len(table)} + reference {len(ref)} = {len(union)} / {len(rules)} rules")
